name: DEV > Docker

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:   
  build:    
    runs-on: ubuntu-latest   
    env:
      DOCKER_TARGET_PLATFORM: linux/arm64
      DOCKER_IMAGE: mimosa-spotify
    steps:
    # checkout 
    - name: Checkout 
      uses: actions/checkout@v3

    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2   

    # https://github.com/docker/metadata-action
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ghcr.io/${{ github.actor }}/${{ env.DOCKER_IMAGE }}
        tags: |
            type=ref,event=branch
            type=sha

    # https://github.com/docker/login-action
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
    
    # https://github.com/docker/build-push-action
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        platforms: ${{ env.DOCKER_TARGET_PLATFORM }}
        labels: ${{ steps.meta.outputs.labels }}